title: Taller de Videojocs
description: Optativa 2SMX
theme: just-the-docs

url: https://jaume-av.github.io/ProgramacioSMX/

search_enabled: true

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  nota:
    title: Nota
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
